### ISSUE TITLE
View för visa objekt(4)

### ISSUE THREAD

**Issue by ghost** [AdaptiveStep/G2Libsys#2]
┆Issue is synchronized with this [Trello card](https://trello.com/c/48SII5tZ) by [Unito](https://www.unito.io/learn-more)

**Comment by Caoabc123** [comment]
View för visa objekt(4). Please change doing to done in sprint 1 for https://trello.com/c/48SII5tZ/48-view-f%C3%B6r-visa-objekt4. Tack.
